id: cisco-network-config

info:
  name: Cisco System Network Configuration Page - Detect
  author: DhiyaneshDk
  severity: info
  description: Cisco System Network configuration page was detected. Page lists whole network configuration and internal logs of Cisco IP phones.
  reference:
    - https://www.exploit-db.com/ghdb/5430
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,cisco,edb,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/CGI/Java/Serviceability?adapter=device.statistics.configuration"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Network Configuration"
        part: body

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100813e9973d7d1eb4268049f244920487c3e1e8c5f9b58215265196a714355dc5402205619213595d60a04fcca831907236db30ba7efba530002f8c6b8637ace9f53dc:922c64590222798bb761d5b6d8e72950
