id: tugboat-config-exposure

info:
  name: Tugboat Configuration File Exposure
  author: geeknik
  severity: critical
  description: A Tugboat configuration file was discovered. Tugboat is a command line tool for interacting with DigitalOcean droplets.
  reference:
    - https://github.com/petems/tugboat
    - https://www.digitalocean.com/community/tools/tugboat
  metadata:
    max-request: 1
  tags: tugboat,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.tugboat"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "authentication"
          - "access_token"
          - "ssh_user"
        condition: and

    extractors:
      - type: regex
        part: body
        regex:
          - 'access_token: .*'

# digest: 490a00463044022044ba5a9cc391f1d911f38deb3ebf26f41aa80753adbab67f6bac37728dc0c3d4022020e1f97ede0a1d31cc671bff6150ce3c496b3209052e48c889a765f202d925ca:922c64590222798bb761d5b6d8e72950
