id: wordpress-git-config

info:
  name: Wordpress Git Config
  author: nerrorsec
  severity: info
  description: Searches for the pattern /.git/config inside themes and plugins folder.
  reference:
    - https://hackerone.com/reports/248693
  metadata:
    max-request: 2
  tags: hackerone,config,git,exposure,wordpress,wp-plugin,wp-theme

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/.git/config"
      - "{{BaseURL}}/wp-content/themes/.git/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[core]"

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and

      - type: status
        status:
          - 200

# digest: 490a0046304402200c85e6bde7f8fd5a418f6ae475ea3e43619b2c9bbdaa025a2ff0a3467f271cc802204e6427102c1fe622a829ec9df5831e46740d60b9bf8eec9d72ecd086068a28de:922c64590222798bb761d5b6d8e72950
