id: manageengine-applications-manager

info:
  name: ZOHO ManageEngine Applications Manager Panel - Detected
  author: dhiyaneshDK
  severity: info
  description: ZOHO ManageEngine panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,zoho,manageengine

http:
  - method: GET
    path:
      - '{{BaseURL}}/index.do'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100f4c5cd3df1744e754568c7404a238381e00ad9c3d76e69cbeb3e44c6b4c13ef4022005ff123ff9d2672aea87544607f24a46ba1303525e52d1c022a699d9c184bdff:922c64590222798bb761d5b6d8e72950
