id: honeywell-scada-config

info:
  name: Honeywell Scada Configuration File - Detect
  author: alperenkesk
  severity: low
  description: Honeywell Scada configuration file was detected. The downloaded file opens with the file name and contains critical information about the destination address.
  reference:
    - https://www.exploit-db.com/exploits/44734
  metadata:
    max-request: 1
  tags: scada,config,exposure,edb

http:
  - method: GET
    path:
      - "{{BaseURL}}/web_caps/webCapsConfig"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DeviceSubClass"
          - "IPAddress"
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100c0f2016a461df23affb3b5ae7fd44f8d3f692b3176a15e75db0921700de218e9022076e3f33b720ab87a3c83373e9ff362dac91db2a07c0bdb573bbbc1b2bb334e53:922c64590222798bb761d5b6d8e72950
