id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155
  severity: info
  metadata:
    max-request: 6
  tags: misc,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/example.htaccess"
      - "{{BaseURL}}/_.htaccess"
      - "{{BaseURL}}/sample.htaccess"
      - "{{BaseURL}}/a.htaccess"
      - "{{BaseURL}}/htaccess_for_page_not_found_redirects.htaccess"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - RewriteRule
          - </IfModule>
          - <IfModule
        condition: and

# digest: 4a0a00473045022100b85760f34954f690a0df1fa6ecfbf714c0b77bf4932bdef641e8fac0098118e80220557cf6c427f31e2cce8de948f0eb6c9574279b5bebad4a0400fb7e2ef02e6ab8:922c64590222798bb761d5b6d8e72950
