id: phpmyadmin-misconfiguration

info:
  name: phpmyadmin Data Exposure
  author: pussycat0x
  severity: medium
  description: An unauthenticated instance of phpmyadmin was discovered, which could be leveraged to access sensitive information.
  reference:
    - https://www.exploit-db.com/ghdb/6997
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: phpmyadmin,misconfig,edb

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/index.php?db=information_schema"
      - "{{BaseURL}}/phpMyAdmin/index.php?db=information_schema"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "var db    = 'information_schema';"
          - "var opendb_url = 'db_structure.php';"
        condition: and

      - type: status
        status:
          - 200

# digest: 4b0a00483046022100bafc9995417fdfa25dfa4668c17078ba4eca8a651519f90621f80445d32077ea022100811967bf5e1a02340f7a28605ea12c663109d298d155002f5f00abaa3d79c4c9:922c64590222798bb761d5b6d8e72950
