id: prometheus-exposed-panel

info:
  name: Prometheus Panel - Detect
  author: organiccrap
  severity: info
  description: Prometheus panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,prometheus

http:
  - method: GET
    path:
      - '{{BaseURL}}/graph'

    matchers:
      - type: word
        words:
          - '<title>Prometheus Time Series Collection and Processing Server</title>'

# digest: 4b0a00483046022100e92957010c8422e84200bd7fd894f4516c5ce701e407477377670f7144709f6d022100ebaa16251acba5575537412e3c0c699e73dbdeb085d57970c4da991806bf0203:922c64590222798bb761d5b6d8e72950
