id: prometheus-pushgateway-exposed-panel

info:
  name: Prometheus Pushgateway Panel - Detect
  author: codexlynx
  severity: info
  description: Prometheus Pushgateway panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,prometheus,pushgateway

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - '<title>Prometheus Pushgateway</title>'

# digest: 4a0a00473045022012a172dc6ea69f2b61efabcab3d18a1fab5b5b82e49cece7c5d8f44055035ce5022100dfc18f9ac53c6f3e85c259c2e115b6806ac595358a2de4f9eb6c5aed7d2bf9aa:922c64590222798bb761d5b6d8e72950
